### ISSUE TITLE
Another IE 7 comma issue

### ISSUE THREAD

**Issue by rvitasek** [buildinternet/totem#2]
Hi there,
first I'd like to thank you for this awesome script as it is exactly what was looking for for some time. The only issue I had with the demo (both online and the latest version downloaded from the github) is in IE7 where it apparently doesn't like the comma at the very last line of the options code...e.g. mousestop : true, makes the script not to work in IE7. By removing the comma everything is working fine then.

Also not sure why bullet points of the list show in IE7 but disappear it oher browsers after running the script. This is not really an issue as it can be easily fixed in CSS but I thought you should be aware of that...

Cheers,

floutag

**Comment by zachdunn** [comment]
After a bit of a hiatus from the project, I'm updating the demo files to fix the the hanging comma issue with IE7. Also, I've added a `list-style:none;` to the default stylesheet in an effort to fix the bullet points showing in IE7.
